version: 2.1


jobs:
  build:
    docker:
        - image: cimg/php:8.0
    working_directory:  ~/project/leet_combination_generator
    steps:
      - run:
          name: "Just printing"
          command: for entry in /home/circleci/*; do echo "$entry"; done
      - run:
          name: "Setting up Composer"
          command: composer install -n --prefer-dist
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit