version: 2.1


jobs:
  build:
    docker:
        - image: cimg/php:8.0.3
    steps:
      - run:
          name: "Setting up Composer"
          command: composer dump
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit