version: 2.1


jobs:
  build:
    docker:
        - image: cimg/php:8.0.3
    working_directory: ~/leet_combination_generator
    steps:
      - run:
          name: "Just printing"
          command: ls
      - run:
          name: "Setting up Composer"
          command: composer install -n --prefer-dist
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit