version: 2.1


jobs:
  build:
    docker:
        - image: cimg/php:8.0
    working_directory:  ~/project
    steps:
      - run:
          name: "Cloning repo"
          command:
            git clone https://github.com/Ellyzeul/leet_combination_generator.git;
      - run:
          name: "Setting up Composer"
          command:
            cd /home/circleci/project/leet_combination_generator;
            composer install -n --prefer-dist
      - run:
          name: "Run Tests"
          command:
            cd /home/circleci/project/leet_combination_generator;
            ./vendor/bin/phpunit