version: 2.1


jobs:
  build:
    docker:
        - image: cimg/php:8.0
    steps:
      - run:
          name: "Just printing"
          command: cat composer.json
      - run:
          name: "Setting up Composer"
          command: composer install -n --prefer-dist
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit